const illustrationsInfo = [
  {
    community:'cerro-de-leones',
    cloudsCommunity:{distance:185, direction:'-'},
    villageColorsCommunity:['houses-left', 'houses-right', 'trees'],
    animalsCommunity:[{id:'cow', selector:''}, {id:'chicken', selector:''}],
    animalsDistance:[{id:'cow', selector:''}, {id:'chicken', selector:''}],
    animalsSolution:[{id:'cow', selector:''}, {id:'chicken', selector:''}],
    numberOfBirdsDistance:2,
    directionBirdsDistance:'right',
    numberOfBirdsSolution:2,
    directionBirdsSolution:'left',
    vehicleCommunity:{distance:80, direction:'+', rotationWheelBack:456, rotationWheelFront:599},
    missedSchoolHours:{min:12, max:15},
    hasTwoSchools:true,
    waterContaminants:{biological:7, inorganic:6}
  },
  {
    community:'las-mercedes-km11',
    animalsCommunity:[{id:'chicken1', selector:''}, {id:'chicken2', selector:''}],
    animalsDistance:[{id:'chicken1', selector:''}, {id:'chicken2', selector:''}],
    animalsSolution:[{id:'cow', selector:''}, {id:'chicken', selector:''}],
    numberOfBirdsDistance:2,
    directionBirdsDistance:'left',
    numberOfBirdsSolution:3,
    directionBirdsSolution:'left',
    vehicleCommunity:{distance:60, direction:'+', rotationWheelBack:814, rotationWheelFront:814},
    missedSchoolHours:{min:3, max:3},
    hasTwoSchools:false,
    waterContaminants:{biological:6, inorganic:5}
  },
  {
    community:'la-merced',
    animalsCommunity:[{id:'chicken1', selector:''}, {id:'chicken2', selector:''}],
    animalsDistance:[{id:'chicken1', selector:''}, {id:'chicken2', selector:''}],
    animalsSolution:[{id:'chicken1', selector:''}, {id:'chicken2', selector:''}],
    numberOfBirdsDistance:0,
    directionBirdsDistance:'',
    numberOfBirdsSolution:2,
    directionBirdsSolution:'left',
    vehicleCommunity:{distance:120, direction:'+', rotationWheelBack:1378, rotationWheelFront:1378},
    missedSchoolHours:{min:4, max:7},
    hasTwoSchools:true,
    waterContaminants:{biological:6, inorganic:3}
  },
  {
    community:'totoral-bajo',
    animalsCommunity:[{id:'chicken1', selector:''}, {id:'chicken2', selector:''}],
    animalsDistance:[{id:'chicken1', selector:''}, {id:'chicken2', selector:''}],
    animalsSolution:[{id:'chicken1', selector:''}, {id:'chicken2', selector:''}],
    numberOfBirdsDistance:4,
    directionBirdsDistance:'left',
    numberOfBirdsSolution:1,
    directionBirdsSolution:'left',
    vehicleCommunity:{distance:62, direction:'-', rotationWheelBack:362, rotationWheelFront:476},
    missedSchoolHours:{min:8, max:11},
    hasTwoSchools:true,
    waterContaminants:{biological:7, inorganic:3}
  },
  {
    community:'las-mercedes',
    animalsCommunity:[{id:'cow1', selector:''}, {id:'cow2', selector:''}],
    animalsDistance:[{id:'cow1', selector:''}, {id:'cow2', selector:''}],
    animalsSolution:[{id:'chicken', selector:''}, {id:'cow', selector:''}],
    numberOfBirdsDistance:2,
    directionBirdsDistance:'left',
    numberOfBirdsSolution:2,
    directionBirdsSolution:'right',
    vehicleCommunity:{distance:260, direction:'-', rotationWheelBack:1519, rotationWheelFront:1997},
    missedSchoolHours:{min:3, max:3},
    hasTwoSchools:false,
    waterContaminants:{biological:6, inorganic:2}
  },
  {
    community:'totoral-alto',
    animalsCommunity:[{id:'cow', selector:''}],
    animalsDistance:[{id:'cow', selector:''}],
    animalsSolution:[{id:'cow', selector:''}],
    numberOfBirdsDistance:0,
    directionBirdsDistance:'',
    numberOfBirdsSolution:3,
    directionBirdsSolution:'left',
    vehicleCommunity:{distance:120, direction:'+', rotationWheelBack:1378, rotationWheelFront:1378},
    missedSchoolHours:{min:3, max:3},
    hasTwoSchools:false,
    waterContaminants:{biological:7, inorganic:3}
  },
  {
    community:'carrizalillo',
    animalsCommunity:[{id:'cow', selector:''}],
    animalsDistance:[{id:'cow', selector:''}],
    animalsSolution:[{id:'cow', selector:''}],
    numberOfBirdsDistance:2,
    directionBirdsDistance:'left',
    numberOfBirdsSolution:0,
    directionBirdsSolution:'',
    vehicleCommunity:{distance:106, direction:'-', rotationWheelBack:1438, rotationWheelFront:1438},
    missedSchoolHours:{min:3, max:3},
    hasTwoSchools:false,
    waterContaminants:{biological:6, inorganic:5}
  }
];